application: hive-platform
runtime: custom
env: flex

runtime_config:
 document_root: public

handlers:
- url: /.*
  script: public/index.php

skip_files:
- .env
- .idea

beta_settings:
  cloud_sql_instances: hive-platform:us-central1:hive


env_variables:
 APP_ENV: debug
 APP_LOG: errorlog
 APP_KEY: base64:YEnQmBf6a1oscSC7ZZd8y3zKyqb/Cj1gZ63I0xGlavI=
 DB_CONNECTION: mysql
 DB_PORT: 3306
 DB_HOST: localhost
 DB_USERNAME: root
 DB_PASSWORD: H1vE4AnimA1$
 DB_DATABASE: hive
 DB_SOCKET: "/cloudsql/hive-platform:us-central1:hive"
 STORAGE_DIR: /tmp
