runtime: php
env: flex

runtime_config:
 document_root: public

skip_files:
- .env

beta_settings:
  cloud_sql_instances: "afa-database:us-central1:hive"


env_variables:
 APP_ENV: production
 APP_DEBUG: false
 APP_FULL_NAME: "America For Animals - DEV"
 APP_LOG: errorlog
 APP_KEY: "base64:YEnQmBf6a1oscSC7ZZd8y3zKyqb/Cj1gZ63I0xGlavI="
 DB_CONNECTION: mysql
 DB_HOST: localhost
 DB_USERNAME: hive
 DB_PASSWORD: bfef1515
 DB_DATABASE: hive
 DB_SOCKET: "/cloudsql/afa-database:us-central1:hive"
 STORAGE_DIR: /tmp
